(() => {
const $=s=>document.querySelector(s), L=()=>document.documentElement.lang==='en'?1:0;
const pair=(es,en)=>[es,en];
const scene=(time,title,text,img,enTime,enTitle,enText,note='',enNote='',optional=false)=>({time:pair(time,enTime),title:pair(title,enTitle),text:pair(text,enText),img,note:pair(note,enNote),optional});
const exp='assets/experiencias/';
const lima='assets/lima/',dest='assets/destinos/',photo='assets/relatos/';
const stories=[
{id:'lima',name:pair('Un día en Lima','A day in Lima'),subtitle:pair('Historia, sabores y un día que cambia de escenario.','History, flavours and a day of changing scenery.'),tail:pair('No tienes que hacerlo todo. Tu día perfecto tiene espacio para disfrutar.','You do not need to do it all. Your perfect day leaves space to enjoy it.'),scenes:[
scene('La mañana','Lima abre sus puertas.','Empezamos entre las plazas y balcones de Lima colonial. Si te atrae su lado religioso, sumamos San Francisco y el misterio de sus catacumbas. La mañana sigue tus curiosidades.',lima+'colonial.webp','Morning','Lima opens its doors.','Start among the squares and balconies of colonial Lima. If its spiritual side intrigues you, add San Francisco and its mysterious catacombs. Your curiosity shapes the morning.'),
scene('El almuerzo','Lima se cuenta en la mesa.','Después de caminar, llega una pausa con sabor a Perú. Ceviche o cocina criolla: elegimos la mesa según tus gustos.',lima+'gastronomia.webp','Lunch','Lima tells its story at the table.','After a walk, pause for a taste of Peru. Ceviche or Creole cooking: we choose the table around your tastes.'),
scene('La tarde','El Pacífico, bajo tus pies.','En la Costa Verde, la ciudad se mira desde otra altura. ¿Parapente o un paseo por el malecón? Tú decides cómo sentir el mar.',lima+'parapente.webp','Afternoon','The Pacific beneath your feet.','Discover a different perspective on Costa Verde. Paragliding or a walk along the cliffs? Choose how you want to feel the sea.','Parapente opcional, sujeto al clima y evaluación del operador.','Optional paragliding, subject to weather and operator assessment.',true),
scene('La caída del sol','Una despedida que se queda.','Bajamos el ritmo frente al océano. Chorrillos y la leyenda del Salto del Fraile ponen el relato; el horizonte, el resto.',lima+'fraile.webp','Sunset','A farewell that stays with you.','Slow down by the ocean. Chorrillos and the legend of Salto del Fraile tell the story; the horizon does the rest.'),
scene('La cena','El aroma de una noche limeña.','La brasa anuncia los anticuchos. Una cena para descubrir sabores locales y conversar sobre lo vivido.',photo+'anticuchos.webp','Dinner','The aroma of a Lima evening.','The grill announces anticuchos. Discover local flavours over dinner and talk about the day.'),
scene('La noche','El día termina en luz.','El Circuito Mágico del Agua cambia el escenario con fuentes, música y luces. Un final distinto para un día muy tuyo.',photo+'agua.webp','Night','The day ends in light.','The Magical Water Circuit changes the scene with fountains, music and light. A different ending to a day that is yours.','Lo incluimos según horarios, traslados y la energía que quieras darle al día.','Included around opening hours, transfers and how active you want your day to be.',true)
]},
{id:'paracas',name:pair('Paracas e Ica','Paracas & Ica'),subtitle:pair('Un día entre el océano y un mar de arena.','A day between the ocean and a sea of sand.'),tail:pair('Para disfrutarlo, planteamos una salida muy temprana o dormir antes en Paracas. Podemos repartir la ruta en dos días.','Enjoy it with a very early start or an overnight stay in Paracas. We can spread the route across two days.'),scenes:[
scene('Temprano','El mar tiene otros habitantes.','Desde Paracas, salimos hacia Ballestas. Lobos marinos, aves y el Candelabro nos recuerdan que el paisaje también está vivo.',photo+'paracas.webp','Early morning','The sea has other inhabitants.','From Paracas, head towards Ballestas. Sea lions, birds and the Candelabra remind us the landscape is alive.','Navegación sujeta a las condiciones del mar.','Boat trips depend on sea conditions.'),
scene('La pausa','Una mesa entre mar y desierto.','Nos detenemos a comer y respirar. El almuerzo se adapta a tu paladar antes de seguir hacia Ica.',exp+'picnic-paracas.webp','The pause','A table between sea and desert.','Stop for lunch and a breath. The meal follows your tastes before continuing towards Ica.'),
scene('La tarde','Un oasis que parece imposible.','Huacachina aparece entre dunas. Caminamos, miramos y elegimos: contemplar el oasis o sumar aventura en la arena.',exp+'oasis.webp','Afternoon','An oasis that seems impossible.','Huacachina appears among the dunes. Walk, admire and choose: take in the oasis or add a sand adventure.'),
scene('El atardecer','La arena también guarda recuerdos.','Buscamos tu forma de vivir el desierto: una vista al caer el sol, aventura en dunas o una experiencia adicional con camellos si está disponible.','assets/experiencias/desierto.webp','Sunset','Sand holds memories too.','Find your way to enjoy the desert: a sunset view, dune adventures or an additional camel experience if available.','Camellos y actividades de aventura opcionales, según disponibilidad.','Camels and adventure activities are optional, subject to availability.',true)
]},
{id:'cusco',name:pair('Cusco y Machu Picchu','Cusco & Machu Picchu'),subtitle:pair('Varios días. Cada maravilla con su propio tiempo.','Several days. Each wonder with its own time.'),tail:pair('Machu Picchu y Siete Colores se viven en jornadas distintas. Diseñamos el orden con tiempo para aclimatarte y disfrutar.','Machu Picchu and Rainbow Mountain belong on different days. We plan time to acclimatise and enjoy the journey.'),scenes:[
scene('La bienvenida','Primero, encuentra tu ritmo.','Te recibimos y damos espacio para adaptarte a la altura. La primera experiencia es llegar con calma y sentir los Andes.',exp+'andes-1.webp','The welcome','First, find your pace.','We welcome you and leave space to adjust to the altitude. The first experience is arriving calmly and feeling the Andes.'),
scene('El día de Machu Picchu','Ese momento en que todo se detiene.','La ciudadela aparece entre montañas. Recorremos el circuito reservado con tu guía y tiempo para entender lo que estás mirando.',photo+'machu.webp','Machu Picchu day','The moment everything stands still.','The citadel appears among mountains. Explore your reserved circuit with a guide and time to understand what you see.','Circuito y horario sujetos a entradas disponibles.','Circuit and visiting time depend on ticket availability.'),
scene('Otra jornada','El Valle Sagrado también te espera.','Terrazas de Moray, pueblos y paisajes andinos. Elegimos qué descubrir según tus intereses, dejando a cada lugar el tiempo que merece.',exp+'andes-0.webp','Another day','The Sacred Valley awaits too.','Moray terraces, villages and Andean landscapes. Choose what to discover around your interests, leaving each place the time it deserves.','Ruta opcional, diseñada como una jornada distinta.','Optional route planned as a separate day.',true),
scene('Una jornada aparte','Los Andes cambian de color.','Siete Colores merece su propio día. Después de aclimatarnos, evaluamos una caminata que se ajuste a tu condición y ganas de aventura.',photo+'colores.webp','A separate day','The Andes change colour.','Rainbow Mountain deserves its own day. After acclimatisation, consider a hike that suits your fitness and appetite for adventure.','Jornada opcional según aclimatación, condición física y clima.','Optional day depending on acclimatisation, fitness and weather.',true)
]},
{id:'norte',name:pair('Máncora y playas','Máncora & beaches'),subtitle:pair('El día perfecto también puede tener pocas prisas.','A perfect day can be an unhurried one.'),tail:pair('Máncora, Vichayito, Punta Sal o Los Órganos. Elegimos la base que encaje contigo, sin encadenar todas las playas.','Máncora, Vichayito, Punta Sal or Los Órganos. Choose the base that suits you, without rushing through every beach.'),scenes:[
scene('La mañana','Despierta cerca del mar.','Una caminata por la arena y tiempo para mirar las olas. Diseñamos el día desde la playa que elijas como base.',exp+'surf-norte.webp','Morning','Wake up near the sea.','Walk along the sand and take time to watch the waves. Your chosen beach becomes your base.'),
scene('El almuerzo','El norte tiene su propio sabor.','Una pausa de cocina marina y conversación. Elegimos opciones que se ajusten a tus gustos y necesidades.',exp+'cocina.webp','Lunch','The north has its own flavour.','Pause for seafood and conversation. Choose options that fit your tastes and needs.'),
scene('La tarde','Descansar también es viajar.','Un libro, la orilla o una actividad en el mar. Tú marcas cuánto movimiento quieres en tu día.',exp+'vichayito.webp','Afternoon','Resting is travelling too.','A book, the shoreline or a sea activity. Choose how active you want your day to be.'),
scene('El cierre','Quédate un poco más.','El horizonte invita a bajar el ritmo. Una cena tranquila y la sensación de haber tenido el día para ti.',dest+'playas.webp','The ending','Stay a little longer.','The horizon invites you to slow down. A peaceful dinner and the feeling that the day was yours.')
]},
{id:'selva',name:pair('Selva central','Central rainforest'),subtitle:pair('Chanchamayo y La Merced: agua, aromas y vida.','Chanchamayo and La Merced: water, aromas and life.'),tail:pair('La Merced como punto de partida; cataratas y café según tu tiempo. Tarma, Tarapoto y Tingo María tienen sus propios recorridos.','Start in La Merced; add waterfalls and coffee around your time. Tarma, Tarapoto and Tingo María each have their own routes.'),scenes:[
scene('La mañana','La selva te recibe despierta.','Desde La Merced, comenzamos entre paisajes tropicales. Tu guía pone nombre a las historias del lugar.',dest+'la-merced.webp','Morning','The rainforest welcomes you awake.','From La Merced, start among tropical landscapes. Your guide brings local stories to life.'),
scene('El encuentro','Sigue el sonido del agua.','Elegimos una catarata como Bayoz según los traslados y la caminata que quieras hacer. La selva se siente de cerca.',dest+'chanchamayo.webp','The encounter','Follow the sound of water.','Choose a waterfall such as Bayoz around transfers and the walk you want to take. Get closer to the rainforest.'),
scene('La pausa','Este viaje también tiene aroma.','El café cuenta otra historia de Chanchamayo. Podemos sumar una visita para descubrir de dónde viene cada taza.',dest+'cafe.webp','The pause','This journey has its own aroma.','Coffee tells another Chanchamayo story. Add a visit to discover where each cup comes from.','Visitas según disponibilidad de la experiencia local.','Visits depend on local experience availability.'),
scene('La tarde','Vuelve con otra mirada.','Una pausa para comer, conversar y disfrutar del paisaje. Volvemos a tu base sin convertir el día en una carrera.',exp+'tirol.webp','Afternoon','Return with a new perspective.','Pause for food, conversation and scenery. Return to your base without turning the day into a race.')
]},
{id:'huancaya',name:pair('Huancaya','Huancaya'),subtitle:pair('Montañas, cascadas y tiempo para respirar.','Mountains, cascades and time to breathe.'),tail:pair('La llegada también necesita tiempo. Diseñamos la escapada con noches y traslados que permitan disfrutar del paisaje.','Getting here takes time too. Plan nights and transfers that leave room to enjoy the landscape.'),scenes:[
scene('Al despertar','Hay lugares que bajan el volumen.','Despiertas entre montañas. Dejamos que la mañana empiece con el paisaje, sin perseguir una lista de paradas.',dest+'huancaya.webp','Waking up','Some places turn down the volume.','Wake among mountains. Let the morning start with the landscape instead of a list of stops.'),
scene('La caminata','El agua dibuja el camino.','Cascadas y pozas cambian la vista a cada paso. Elegimos una caminata que se ajuste a tu ritmo.',exp+'yauyos-3.webp','The walk','Water draws the path.','Cascades and pools change the view at every turn. Choose a walk that suits your pace.'),
scene('La pausa','El mejor plan: quedarse a mirar.','Una pausa de comida local y tiempo para fotografías. Hay recuerdos que necesitan un rato más.',exp+'yauyos-4.webp','The pause','The best plan: stay and watch.','Pause for local food and photographs. Some memories need a little more time.')
]}
];
const copy={label:pair('IMAGINA EL DÍA. NOSOTROS DISEÑAMOS EL VIAJE.','IMAGINE THE DAY. WE DESIGN THE JOURNEY.'),heading:pair('Diseñamos tus días perfectos.<br>A tu ritmo. A tu manera.','We design your perfect days.<br>At your pace. In your own way.'),intro:pair('Una mañana de historia. Una tarde sobre el mar. Una mesa que recordarás. Diseñamos tus días alrededor de lo que te mueve.','A morning of history. An afternoon by the sea. A meal to remember. We design your days around what moves you.'),pick:pair('Diseñemos mi versión de este viaje','Design my own version of this journey'),note:pair('Una idea para inspirarte. Ajustamos tiempos, traslados y actividades contigo. Fotografías de referencia.','An idea to inspire you. We adjust timings, transfers and activities with you. Reference photographs.'),more:pair('EL PERÚ QUE CONOCES. Y EL QUE TE FALTA DESCUBRIR.','THE PERU YOU KNOW. AND THE PERU STILL TO DISCOVER.')};
let region=0,moment=0,rhythm='aventura';
function scenes(){const s=stories[region].scenes;return rhythm==='calma'?s.filter(x=>!x.optional):s;}
function render(){
 const focused=document.activeElement;const focusKey=focused?.dataset.region!==undefined?['region',focused.dataset.region]:focused?.dataset.moment!==undefined?['moment',focused.dataset.moment]:null;
 const l=L(),s=stories[region],list=scenes();moment=Math.max(0,Math.min(moment,list.length-1));const current=list[moment];
 document.querySelectorAll('[data-story-copy]').forEach(el=>el.innerHTML=copy[el.dataset.storyCopy][l]);
 $('#story-regions').innerHTML=stories.map((s,i)=>`<button type="button" data-region="${i}" aria-pressed="${i===region}">${s.name[l]}</button>`).join('');
 $('#story-place').textContent=s.name[l];$('#story-subtitle').textContent=s.subtitle[l];
 $('#story-rhythm').querySelectorAll('button').forEach(b=>{b.textContent=b.dataset.rhythm==='calma'?(l?'Unhurried':'Sin prisa'):(l?'More experiences':'Más experiencias');b.setAttribute('aria-pressed',String(b.dataset.rhythm===rhythm));});
 const image=$('#story-image');const changed=image.getAttribute('src')!==current.img;image.src=current.img;image.alt=current.title[l];if(changed&&!matchMedia('(prefers-reduced-motion: reduce)').matches)image.animate([{opacity:.45,transform:'scale(1.025)'},{opacity:1,transform:'scale(1)'}],{duration:500,easing:'ease-out'});$('#story-image-caption').textContent=s.name[l];
 for(const [id,delta] of [['story-before',-1],['story-after',1]]){const b=$('#'+id),i=moment+delta;b.disabled=i<0||i>=list.length;b.style.visibility=b.disabled?'hidden':'visible';b.style.backgroundImage=`url("${list[Math.max(0,Math.min(i,list.length-1))].img}")`;b.setAttribute('aria-label',l?(delta<0?'Previous moment':'Next moment'):(delta<0?'Momento anterior':'Momento siguiente'));}
 $('#story-moment').textContent=current.time[l];$('#story-title').textContent=current.title[l];$('#story-text').textContent=current.text[l];$('#story-condition').textContent=current.note[l];
 for(const [id,es,en] of [['story-regions','Elige un relato de viaje','Choose a journey'],['story-rhythm','Tu ritmo','Your pace'],['story-stage','Carrusel de momentos del viaje','Journey moments carousel'],['story-moments','Momentos del relato','Story moments'],['story-prev','Momento anterior','Previous moment'],['story-next','Momento siguiente','Next moment']])$('#'+id).setAttribute('aria-label',l?en:es);
 $('#story-position').textContent=`${moment+1} / ${list.length}`;$('#story-prev').disabled=moment===0;$('#story-next').disabled=moment===list.length-1;
 $('#story-moments').innerHTML=list.map((x,i)=>`<button type="button" data-moment="${i}" aria-pressed="${i===moment}"><span class="moment-dot" aria-hidden="true"></span>${x.time[l]}</button>`).join('');
 $('#story-tail').textContent=s.tail[l];if(focusKey)document.querySelector(`[data-${focusKey[0]}="${focusKey[1]}"]`)?.focus({preventScroll:true});
 const selected=$('#story-moments').querySelector('[aria-pressed="true"]');if(selected)$('#story-moments').scrollTo({left:Math.max(0,selected.offsetLeft-$('#story-moments').offsetLeft-20),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});
 const destinations=[['Machu Picchu','assets/relatos/machu.webp','machu-picchu-cusco.html'],['Huacachina',exp+'oasis.webp','paracas-huacachina.html'],['Paracas','assets/relatos/paracas.webp','paracas-huacachina.html'],['Máncora',exp+'mar-norte.webp','mancora-playas.html'],['Huancaya',exp+'yauyos-2.webp','huancaya.html'],['Tarapoto',dest+'tarapoto.webp','tarapoto.html'],['Tingo María',dest+'tingo-maria.webp','tingo-maria.html'],['Tarma',dest+'tarma.webp','selva-central.html#tarma'],['Chanchamayo',exp+'puente-kimiri.webp','selva-central.html'],['La Merced',exp+'mirador-merced.webp','selva-central.html']];
 $('#story-more').innerHTML=destinations.map(([n,img,url])=>`<a href="${url}"><img src="${img}" alt="${n}" loading="lazy" width="240" height="150">${n}<span aria-hidden="true">↗</span></a>`).join('');
 $('#story-pick').href=journeyLink(s.name[l]);
}
function move(delta){moment=Math.max(0,Math.min(moment+delta,scenes().length-1));render();}
$('#story-regions').addEventListener('click',e=>{const b=e.target.closest('[data-region]');if(b){region=Number(b.dataset.region);moment=0;render();}});
$('#story-moments').addEventListener('click',e=>{const b=e.target.closest('[data-moment]');if(b){moment=Number(b.dataset.moment);render();}});
$('#story-rhythm').addEventListener('click',e=>{const b=e.target.closest('[data-rhythm]');if(b){rhythm=b.dataset.rhythm;moment=0;render();}});
for(const [id,d] of [['story-prev',-1],['story-before',-1],['story-next',1],['story-after',1]])$('#'+id).addEventListener('click',()=>move(d));
$('#story-stage').addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1);}});
let start=null;$('#story-stage').addEventListener('pointerdown',e=>{if(e.pointerType==='touch')start={x:e.clientX,y:e.clientY};});$('#story-stage').addEventListener('pointerup',e=>{if(start){const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)>50&&Math.abs(dx)>Math.abs(dy))move(dx<0?1:-1);start=null;}});$('#story-stage').addEventListener('pointercancel',()=>start=null);
function journeyLink(place){const l=L();const msg=(l?'Hello PERUGO, I would like to design a journey around ':'Hola PERUGO, me gustaría diseñar un viaje por ')+place+(l?`, at ${rhythm==='calma'?'an unhurried':'a more active'} pace.`:`, a un ritmo ${rhythm==='calma'?'tranquilo':'con más experiencias'}.`);return 'https://wa.me/51954708174?text='+encodeURIComponent(msg);}
document.querySelectorAll('.lang button').forEach(b=>b.addEventListener('click',render));
render();
})();
