import { useEffect, useRef, useState } from 'react';
import Sections from './Sections';
import { ArrowUpRight, ArrowRight, X, Menu, Pause, Play } from 'lucide-react';

const chapters = [
 {label:'El encuentro',title:'Tú pones el equipo.',italic:'Nosotros, el resto.',text:'Cada encuentro empieza mucho antes de entrar a la cancha. Preparamos el espacio y coordinamos cada detalle para que tú te concentres en el fútbol.'},
 {label:'La preparación',title:'Cada detalle cuenta.',italic:'Dentro y fuera de la cancha.',text:'Organización, preparación del campo y coordinación de la jornada. Un solo equipo detrás de todo lo que tu encuentro necesita.'},
 {label:'El pitazo inicial',title:'Todo listo para',italic:'el pitazo inicial.',text:'Preparamos la cancha. Coordinamos cada detalle. Tú solo reúne a tu equipo y disfruta el fútbol. Del primer preparativo al primer pase, estamos contigo.'}
];
export default function App(){
 const [stage,setStage]=useState(2),[menu,setMenu]=useState(false),[contact,setContact]=useState(false),[paused,setPaused]=useState(false);
 const video=useRef<HTMLVideoElement>(null),dialog=useRef<HTMLDialogElement>(null);
 const content=chapters[stage];
 useEffect(()=>{const v=video.current;if(!v)return;let raf=0,timer:ReturnType<typeof setTimeout>;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const tick=()=>{const d=v.duration,t=v.currentTime;v.style.opacity=String(Number.isFinite(d)?Math.max(0,Math.min(1,t/.5,(d-t)/.5)):0);raf=requestAnimationFrame(tick)};
 const ended=()=>{v.style.opacity='0';timer=setTimeout(()=>{v.currentTime=0;v.play().catch(()=>setPaused(true))},100)};
 if(!reduced){v.play().catch(()=>setPaused(true));raf=requestAnimationFrame(tick)}else{setPaused(true)}v.addEventListener('ended',ended);return()=>{cancelAnimationFrame(raf);clearTimeout(timer);v.removeEventListener('ended',ended)}},[]);
 useEffect(()=>{if(contact)dialog.current?.showModal();else dialog.current?.close()},[contact]);
 function select(i:number){setStage(i);setMenu(false)}
 function toggle(){const v=video.current;if(!v)return;if(v.paused)v.play().then(()=>setPaused(false)).catch(()=>setPaused(true));else{v.pause();setPaused(true)}}
 return <><a className="skip-link" href="#contenido">Ir al contenido</a><div id="inicio" className="site relative min-h-screen w-full overflow-hidden">
  <div className="field-layer" aria-hidden="true"><div className="field-still"/><video ref={video} muted playsInline preload="auto" poster="/pitch.jpg" src="/pitch.mp4"/><div className="field-gradient"/></div>
  <header className="relative z-10"><nav className="navigation" aria-label="Navegación principal"><a className="brand" href="#inicio" onClick={()=>select(2)} aria-label="TÁCTICA 11, inicio"><img src="/brand-reference.png" alt="TÁCTICA 11 · Logística deportiva"/></a><div className="desktop-links"><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#clientes">Clientes</a><a href="#galeria">Galería</a></div><button className="button nav-cta" onClick={()=>setContact(true)}>Planifica tu encuentro <ArrowUpRight size={16}/></button><button className="mobile-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'Cerrar menú':'Abrir menú'}>{menu?<X/>:<Menu/>}</button></nav>{menu&&<div className="mobile-menu">{[['Nosotros','nosotros'],['Servicios','servicios'],['Clientes','clientes'],['Experiencias','experiencias'],['Galería','galeria'],['Contacto','contacto']].map(([label,id])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}</div>}</header>
  <section aria-label="Presentación" className="hero relative z-10 flex flex-col items-center text-center px-6"><div className="eyebrow animate-fade-rise"><span className="tiny-line"/>LOGÍSTICA DEPORTIVA · FÚTBOL<span className="tiny-line"/></div><div key={stage} className="hero-copy"><h1 className="animate-fade-rise">{content.title}<br/><em>{content.italic}</em></h1><p className="description animate-fade-rise-delay">{content.text}</p></div><button className="button hero-cta animate-fade-rise-delay-2" onClick={()=>setContact(true)}>Hagamos que suceda <ArrowUpRight size={19}/></button><p className="hero-note animate-fade-rise-delay-2">Tú juegas. Nosotros lo hacemos posible.</p></section>
  <div className="bottom-bar relative z-10"><div className="sequence" aria-label="Cómo preparamos tu encuentro">{chapters.map((item,i)=><button key={item.label} onClick={()=>select(i)} className={stage===i?'selected':''} aria-pressed={stage===i}><span className="step-number">0{i+1}</span><span>{item.label}</span>{stage===i&&<ArrowRight size={14}/>}</button>)}</div><button className="motion-button" onClick={toggle} aria-label={paused?'Reproducir video':'Pausar video'}>{paused?<Play size={15}/>:<Pause size={15}/>}<span>{paused?'Reproducir':'Pausar'} ambiente</span></button></div>
 </div><Sections onContact={()=>setContact(true)}/>
  <dialog aria-labelledby="contact-dialog-title" ref={dialog} onCancel={()=>setContact(false)} onClick={e=>{if(e.target===dialog.current)setContact(false)}}><button className="close-dialog" aria-label="Cerrar" onClick={()=>setContact(false)}><X/></button><span className="dialog-kicker">TU PRÓXIMO ENCUENTRO</span><h2 id="contact-dialog-title">El primer paso<br/><em>empieza contigo.</em></h2><p>Cuéntanos sobre tu encuentro. Te ayudamos a coordinarlo por WhatsApp.</p><form onSubmit={async e=>{e.preventDefault();const data=new FormData(e.currentTarget);const text=`Hola, TÁCTICA 11. Quiero organizar un encuentro de fútbol.\nFecha: ${data.get('fecha')}\nLugar: ${data.get('lugar')}\nEquipos o jugadores: ${data.get('equipos')}\nNecesitamos: ${data.get('detalles')}`;window.open('https://wa.me/51954708174?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')}}><label>Fecha del encuentro<input name="fecha" type="date" required/></label><label>Ciudad o cancha<input name="lugar" placeholder="¿Dónde se juega?" required/></label><label>Equipos o jugadores<input name="equipos" placeholder="Por ejemplo: 4 equipos" required/></label><label>¿Qué necesitas coordinar?<textarea name="detalles" placeholder="Cuéntanos sobre tu encuentro" rows={3}/></label><button className="button" type="submit">Coordinar por WhatsApp <ArrowUpRight size={18}/></button><small>Se abrirá WhatsApp con tu mensaje preparado para TÁCTICA 11.</small></form></dialog>
 </>
}

