import React from 'react';
import { createRoot, hydrateRoot } from 'react-dom/client';
import App from './App';
import './styles/fonts.css';
import './styles/theme.css';
import './styles/sections.css';
const root = document.getElementById('root')!;
const app = <React.StrictMode><App/></React.StrictMode>;
if (root.hasChildNodes()) hydrateRoot(root, app);
else createRoot(root).render(app);
